services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata:/data/db
    networks:
      - backend

volumes:
  dbdata:

networks:
  backend:
    driver: bridge
